### PR TITLE
adding vs template

### PR DESCRIPTION
**Pull request by mustafasaaed**
Adding Visual studio 2017 template to identity server4 using sidewaffle.
this template will generate 4 projects: 

- The Auth Server 
- MVC Web site 
- Web Api 
- A console client 
 this basically will generate these projects and the code is based on the code in the docs module: Using EntityFramework Core for configuration data.

### CODE REVIEW

**Comment by mustafasaaed** [comment]
the build failed because IdentityServerEFTemplatePack is targeting dotnet not dotnetcore 
and this project is from sidewaffle, It builds and works perfectly fine on my machine and it produces the vsix file.

**Comment by leastprivilege** [comment]
Hi, thanks!

In terms of templates, we use the `dotnet new` tooling. See here: 

https://github.com/IdentityServer/IdentityServer4.Templates

We ourselves have no plans to support Sidewaffle - nor can we maintain that. If you want to maintain such templates, please host them yourselves and tell us the URL so we can link to it from our docs.

**Comment by mustafasaaed** [comment]
Hi, @leastprivilege  
thank you for your reply, 
Ok I have created a vs extensions on [vs market place](https://marketplace.visualstudio.com/items?itemName=mustafasaeed.IdentityServerTemplatePack) 

and the source code is on this [repo](https://github.com/mustafasaaed/IdentityServerTemplatePack)
Thank you in advance

**Comment by leastprivilege** [comment]
Thanks!

Could you please change the name to

"IdentityServer Community Template Pack" ?

**Comment by mustafasaaed** [comment]
thanks,
I rename the [repo ](https://github.com/mustafasaaed/IdentityServerCommunityTemplatePack)and the extension to "IdentityServer Community Template Pack"

**Pull request closed without merging**
