### PR TITLE
Included ui_locales as query parameter to ErrorUrl and LogoutUrl

### PR DESCRIPTION
**Pull request by manishandankar**
Included ui_locales as query parameter to ErrorUrl and LogoutUrl 
Fix for Issue https://github.com/IdentityServer/IdentityServer4/issues/1305

Note: 
1.Dependency on IdentityModel changes. Please refer PR : https://github.com/IdentityModel/IdentityModel2/pull/51

2. I have not added the relevant tests yet. All existing tests do pass. Please let me know if the changes look fine fine.

### CODE REVIEW

**Comment by manishandankar** [comment]
I do not understand how to fix the warning "Dependency specified was IdentityModel (>= 2.10.0-build00138) but ended up with IdentityModel 2.10.0. [C:\projects\identityserver4\src\IdentityServer4\IdentityServer4.csproj". This is failing the CI. 
Can you please help me on this ?

**Comment by brockallen** [comment]
I think you have a dependency on a private build of IdentityModel -- is that the problem?

**Comment by brockallen** [comment]
> I think you have a dependency on a private build of IdentityModel -- is that the problem?

Yes/No?

**Comment by leastprivilege** [comment]
Closing this and move to feature request.

**Comment by manishandankar** [comment]
Apologies for the delay in reply. I could not find time to revisit this. 
However, I have been thinking on this for a while and I realized that the urls in the UserInteractionOptions such as  LoginUrl, ErrorUrl and LogoutUrl could actually be locale based configuration. It would be very helpful for applications that deploy with a different subdomains for every language. or even otherwise. They can decide what url to got to for a given locale. Ex: LoginUrl could be LoginUrl with following Dictionary structure, where key is the locale that the application is supporting and a DefaultLoginUrl (as a separate property in the UserInteractionOptions) as a fallback. 
LoginUrls is of type Dictionary<string, string> so that the configuration would look like [{"en", "https://myloginurl/en/"}, {"fr", "https://myloginurl/fr/"}.

Please let me know your thoughts on this.

**Pull request closed without merging**
