### PR TITLE
add bower.json

### PR DESCRIPTION
**Pull request by ateregulov**
For issue #722

### CODE REVIEW

**Comment by brockallen** [comment]
Why?

**Comment by ateregulov** [comment]
It is front-end development guidelines.

**Comment by totht91** [comment]
It's like nuget, if you don't commit the packages folder, you sholdn't commit the wwwroot/libs too.

**Comment by brockallen** [comment]
The host is a sample/testing project, not a production project. I don't see the real need for bower here. If you want bower in your systems, then by all means use it.

**Comment by brockallen** [comment]
Thanks for this, but as I said I think this is something you would just do in your own hosting project.

**Pull request closed without merging**
