### PR TITLE
Add support to carry an error description back to third party clients on authorize error results

### PR DESCRIPTION
**Pull request by MJMortimer**
**What issue does this PR address?**
[Only specific error types can result in a redirect back to the third party client](https://github.com/IdentityServer/IdentityServer4/blob/master/src/Endpoints/Results/AuthorizeResult.cs#L76-L83) and we'd like to give our third party clients more context on why authorization couldn't progress with the use of the error_description query param that's currently not hooked up but is sent back empty.

I think it's related to these open issues
- #1972
- #2031

**Does this PR introduce a breaking change?**
No, shouldn't do

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/dev/.github/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:
This is required following our discussions on our approach to extending the authorize flow for tenanting @brockallen @thirkcircus

### CODE REVIEW

**Comment by brockallen** [comment]
No I didn't, but I'll put a milestone on it to force us to look before we release.

**Comment by arnaldo-infinite** [comment]
Hey, is this feature released already?

**Comment by MJMortimer** [comment]
Hey @brockallen, I see this has been pushed from the 2.4 milestone to 2.5. Just wondering if there's any reason regarding the changes for this?
Cheers

**Comment by MJMortimer** [comment]
@leastprivilege @brockallen  
Any reason why this was closed? Was the work done elsewhere?

**Comment by leastprivilege** [comment]
Sorry - we deleted the dev branch. I didn't expect that this auto-closes the PR.

**Comment by MJMortimer** [comment]
@leastprivilege Seems I can't reopen this PR. I've opened a new one here #3183

**Pull request closed without merging**
