### PR TITLE
Make client secret optional while parsing basic authentication secret

### PR DESCRIPTION
**Pull request by AliBazzi**
This PR add feature request in #2267 ticket

It doesn't introduce breaking change.

### CODE REVIEW

**Comment by AliBazzi** [comment]
Sorry didn't get it, can you elaborate more ?

**Comment by brockallen** [comment]
> Sorry didn't get it, can you elaborate more ?

Well, look at the status:

> Some checks were not successful
> 1 failing and 1 successful checks
> continuous-integration/appveyor/pr — AppVeyor build failed

**Comment by AliBazzi** [comment]
Oh yes, I noticed that, but it looks like it's related to Ubuntu where it failed to compile the integration test project, the windows image with visual studio passed all tests

I don't think the modified unit test broke that project

**Comment by brockallen** [comment]
Ah yes, you're right -- I hadn't followed the link to know it was the unbutu build. I guess something environmental.

**Comment by AliBazzi** [comment]
This is my second PR to Identity server, and both of them were very minimal changes, but my bad luck jumped in the verification process in both PR

**Comment by brockallen** [comment]
No worries. We'll have a look. Thanks

**Comment by AliBazzi** [comment]
Welcome :)

**Comment by leastprivilege** [comment]
Thanks!

Could you also add an integration test - basically a client with empty secret calling into the token endpoint - I want to make sure, nothing breaks later in the pipeline because of a null secret.

**Comment by AliBazzi** [comment]
Sure, working on it :)

**Comment by AliBazzi** [comment]
@leastprivilege please take a look at the integration test when you have time.

**Comment by leastprivilege** [comment]
You also need a test for an empty secret I guess - not just RequireClientSecret = false.

**Comment by leastprivilege** [comment]
Add a client with require secret = true but an empty secret - see if that works as expected.

**Comment by AliBazzi** [comment]
Hi @leastprivilege 

After investigating the code, I think the semantic of empty secret is not supported currently, what is  supported is a client that has RequireClientSecret set to `false`.
When that property is set to `false` it was breaking client id and empty secrets passed in the Basic Authorization header, this PR aimed to fix this bug in `BasicAuthenticationSecretParser`, so adding a test to verify that a client secret empty + RequireClientSecret set to `True` will not pass due to current implementation.

Please advice on the next step and correct me please if I'm wrong.

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
