### PR TITLE
remove extra blank line

### PR DESCRIPTION
**Pull request by adamralph**
As featured in _git commit -m "fix whitespace"_ at [PubConf](https://pubconf.io/) after NDC London 2018.

### CODE REVIEW

**Comment by brockallen** [comment]
seems legit, thanks

**Comment by danielmarbach** [comment]
I'm very worried about the security implications of this change 😂

**Comment by leastprivilege** [comment]
We'll need to run a full pen-test after this change.

**Comment by ThorstenHans** [comment]
lol

**Pull request merged**
