### PR TITLE
Scope claim is always a string array

### PR DESCRIPTION
**Pull request by leastprivilege**

### CODE REVIEW

**Comment by brockallen** [comment]
:shipit: :+1:

**Comment by adminnz** [comment]
There appears to be another issues.

When going through the tutorial in the documentation if you do the switching to hybrid flow (https://identityserver4.readthedocs.io/en/dev/quickstarts/5_hybrid_and_api_access.html) and have a user with multiple roles (e.g. "Admin" and "Developer").

They get combined into 1 claim (type = "role")  with an array value of `["Admin",  "Developer"]`
Where previously when doing Implicit GrantType they would come across as two claims one with "Admin" and the other with "Developer" both claims having the type "role".

**Comment by brockallen** [comment]
Ok, we can look into it. // @leastprivilege

**Comment by brockallen** [comment]
@adminnz Looks like it's a Microsoft bug: https://github.com/aspnet/Security/issues/976

**Pull request merged**
