### PR TITLE
Improve definition of standard scopes from OIDC spec.

### PR DESCRIPTION
**Pull request by diogodamiani**
Defining static read-only properties for standard scopes from OIDC spec. No need to instantiate (use the new operator) each resource.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Dude - thanks. But how about you start a discussion first before you change 16 files?

**Comment by leastprivilege** [comment]
..and why is that an improvement exactly?

**Comment by diogodamiani** [comment]
I'm sorry I did not start a discussion before. :(

I think it's clearer for anyone who uses the code not to instantiate an object that is defined in another class (IdentityResources). When you look for standard types, they are usually in the same class that defines the type.

**Comment by brockallen** [comment]
The reason we changed them to classes to create is to make it easier if the display name or description needed to be changed.

**Comment by diogodamiani** [comment]
Do you mean "needed to be changed" by you or by the consumers of the API? The way it's in the PR allow changes on the default objects if it's necessary, by the spec (you), but not by consumers. 

Anyway, as Dominick said, I should have started a discussion before have sent the PR.

**Comment by brockallen** [comment]
i think we're going to stick with what we have. thanks anyway.

**Pull request closed without merging**
