### PR TITLE
Remove unneeded newlines

### PR DESCRIPTION
**Pull request by danielmarbach**
**At this point we cannot accept PRs for new features, only bugfixes. Thanks!**

**What issue does this PR address?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/main/.github/CONTRIBUTING.md)
- [ ] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by adamralph** [comment]
😍

**Review by adamralph — APPROVED** [review]
how did I miss this?

**Comment by leastprivilege** [comment]
T-Shirt inbound

**Comment by danielmarbach** [comment]
Do I need to sign a CLA? I'm really keen to get this in!

**Comment by adamralph** [comment]
when will this be released?

**Comment by damianh** [comment]
No red-green-refactor. Poor show.

**Comment by danielmarbach** [comment]
Now that I think about it I think these have been semantic newlines! @adamralph @damianh can you help me bring them back as well as introduce more semantic newlines?

**Comment by leastprivilege** [comment]
..actually - changed my mind. I think those whitespace were significant.

**Comment by adamralph** [comment]
If those properties belong to some "group", should that be reflected in the API?

**Comment by brockallen** [comment]
I don't think we went thru the proper review process for this PR, as those newlines *clearly* follow the project coding guidelines, which the OP *obviously* did not read or follow.

**Pull request merged**
