### PR TITLE
Update sample code in docs for G+ deprecation

### PR DESCRIPTION
**Pull request by rbanks54**
**What issue does this PR address?**

#2994 

**Does this PR introduce a breaking change?**

No. Just a docs update.

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/master/.github/CONTRIBUTING.md)
- [ ] Unit Tests for the changes have been added (for bug fixes / features)

No tests - docs update.

**Other information**:

I'll submit a separate PR for the quickstarts.
This PR updates the docs to show the code needed for the G+ deprecation, and adds a note about G+ going away, with a link to the ASP.NET Core docs about the change.

### CODE REVIEW

**Comment by rbanks54** [comment]
Let's hold off merging this PR until I've got the quickstart changes done, given the code really should be in sync between the docs and the quickstarts 🙂

**Comment by rbanks54** [comment]
The other PRs are there now.
IdentityServer/IdentityServer4.Quickstart.UI#46
IdentityServer/IdentityServer4.Samples#282

**Comment by leastprivilege** [comment]
Why is this necessary - Microsoft updated their Google handler - so it works with the new endpoints without code changes.

**Comment by brockallen** [comment]
Since Microsoft has fixed this internally, I think this PR is unnecessary. Thanks though.

**Comment by rbanks54** [comment]
Oh! I didn't notice that they'd fixed it. No problem then.

**Pull request closed without merging**
