### PR TITLE
Add option for having additional claims included when issuing a clien…

### PR DESCRIPTION
**Pull request by rmja**
…t jwt from tools

### CODE REVIEW

**Comment by leastprivilege** [comment]
You see that this calls

return await tools.IssueJwtAsync(lifetime, claims);

in turn?

**Comment by rmja** [comment]
Yes I saw that. I just thought that it would be nice to include it in the convenience extension.

**Comment by leastprivilege** [comment]
IMHO the current API surface enables all the scenarios.

Thanks anyways!

**Comment by rmja** [comment]
Fine with me, I am just spreading my thoughts as I progress in implementing my setup😵 

As an alternative, could we then expose the httpcontext as a public property on the tools instead of it being an internal field? The reason being that I need it in my own custom tools extension method. (I am currently getting it via reflection.)

**Comment by leastprivilege** [comment]
ouch ;)

To get to HttpContext - either pass it in - or inject `IHttpContextAccessor`

**Pull request closed without merging**
