### PR TITLE
Updated cache expiration to use current time

### PR DESCRIPTION
**Pull request by scottbrady91**
**What issue does this PR address?**
Addresses race condition reported in #3860

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/master/.github/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)

### CODE REVIEW

**Comment by brockallen** [comment]
Thanks

**Comment by brockallen** [comment]
@scottbrady91 Do we need to patch this in 3.x?

**Comment by scottbrady91** [comment]
Yeah, please

**Comment by brockallen** [comment]
Ok, cherry picked back to the 3.x branch.

**Pull request merged**
