### PR TITLE
Add remarks about custom implementation of IResourceOwnerPasswordValidator for the corresponding flow.

### PR DESCRIPTION
**Pull request by voroninp**
**What issue does this PR address?**
https://github.com/IdentityServer/IdentityServer4/issues/3839

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ Yes] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/master/.github/CONTRIBUTING.md)
- [ N/A] Unit Tests for the changes have been added (for bug fixes / features)

### CODE REVIEW

**Comment by leastprivilege** [comment]
is 

https://identityserver4.readthedocs.io/en/latest/topics/resource_owner.html 

not good enough?

**Comment by voroninp** [comment]
@leastprivilege  Yep, but it is literally RTFM =)  
Why not let the code tell the story and even better signal about potential problem?

While migrating from IS3 to IS4 we simply forgot to include the call to `AddResourceOwnerValidator` (btw why not ResourceOwnerPasswordValidator`?) =(

**Comment by leastprivilege** [comment]
Because we always have a resource owner password validator registered (to keep DI happy) - just by default one that does nothing - so we cannot easily detect at startup if this is a valid config or not.

**Comment by voroninp** [comment]
@leastprivilege How come? You know the exact type of the default validator, and in case the resolved instance is of this type, IS could warn:
> Hey, man, I see you didn't override default implementation of `IRsourceOwnerPasswordValidator`, but your client `Client` supports `resource owner password` flow. That's not ok.

**Comment by leastprivilege** [comment]
You wanted this at startup time - we are not scanning client configuration at startup time.

**Comment by voroninp** [comment]
Then at least some XML Doc would be helpful, I assume.

**Comment by voroninp** [comment]
BTW, Simple Injector DI container has method `Verify`, maybe it is worth having such diagnostics feature for IS as well.

**Comment by leastprivilege** [comment]
We cannot scan client config - check the `IClientStore`.

There is a configuration validator that could be used for your purpose. Feel free add that logic via a PR.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Validation/Default/DefaultClientConfigurationValidator.cs

**Comment by voroninp** [comment]
@leastprivilege Yep, my bad, this will work fine with InMemory clients only.

**Comment by voroninp** [comment]
@leastprivilege  But what about XML Doc?

**Comment by leastprivilege** [comment]
Closing this in favour of the config validator

**Pull request closed without merging**
