### PR TITLE
Add ApiController attribute

### PR DESCRIPTION
**Pull request by vanillajonathan**
The ApiController attribute is new in ASP.NET Core 2.1.

**What issue does this PR address?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/dev/.github/CONTRIBUTING.md)
- [ ] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by leastprivilege** [comment]
why?

**Comment by vanillajonathan** [comment]
Because the attribute is meant to be used for APIs.
When scaffolding a new ASP.NET Core API project in Visual Studio the controllers use the `ApiController` attribute.
So its just good practice to use the `ApiController` attribute in APIs. It is expected to present in controllers for APIs.

**Comment by brockallen** [comment]
> Because the attribute is meant to be used for APIs.

What is changing or adding beyond what the code already does? IMO, it's unnecessary as the code works fine for what it is illustrating.

**Comment by vanillajonathan** [comment]
It is strictly not needed so it may be left out. But if the code is meant to be copy & pasted then it might be good to provide the attribute as a best practice for building APIs.

**Comment by leastprivilege** [comment]
I don't agree that it is a "best practice". It adds certain conventions and behaviors to a controller. Not everybody might agree with that.

thanks - but closing.

**Pull request closed without merging**
