### PR TITLE
Consent expiration setting

### PR DESCRIPTION
**Pull request by chrisowhite**
Support a consent lifetime to require a resource owner to re-consent

- Required pulling changes for consistent expiration handling in #1135 to allow an expired consent to be returned from the DefaultGrantStore so that it could be checked in DefaultConsentService.RequireConsentAsync()
- Add a ConsentLifetime property to Client model.
- Remove consent from store if expired.
- Add unit tests to validate consent expiration

#951

### CODE REVIEW

**Comment by brockallen** [comment]
We borked the branch and now have conflicts. Mind resubmitting just the changes for the new client setting?

**Comment by chrisowhite** [comment]
I'm on vacation and won't get a chance until later this week if that's alright.

**Comment by brockallen** [comment]
> I'm on vacation and won't get a chance until later this week if that's alright.

Dude, this is OSS -- there are no holidays! J/K, enjoy your time off :)

**Comment by chrisowhite** [comment]
I've pulled dev and fixed the merge conflict. Should be good to go!

**Comment by brockallen** [comment]
Excellent, thanks.

**Pull request merged**
