### PR TITLE
Add JAR support

### PR DESCRIPTION
**Pull request by leastprivilege**
This PR changes the request object logic to be compatible with both OIDC ROs and JAR

### CODE REVIEW

**Comment by uringeller** [comment]
Have you decided on wether or not to handle the "very-special-case" of symmetrically encrypted ROs in a JAR request without OAuth 2.0 parameters (iow: no client_id)?

**Comment by leastprivilege** [comment]
I support both client_id inside only - or in and outside the RO. But inside always takes precedence. And all inside values overwrite the outside values (if that makes sense).

**Comment by steinarnoem** [comment]
That is good! But I was referring to the case where there are no OAuth parameters (outside the RO) and the token, for some unknown reason, is encrypted using a symmetric crypto algorithm. How would you find the correct key to decrypt?
I don't really think that it's a probable scenario, but maybe something that should be explicitly mentioned in the docs? Or just: "use the RAR endpoint to ensure confidentiality" :)

**Comment by leastprivilege** [comment]
Well - this would not work. If it is symmetrically encrypted then the client_id needs to be outside the RO (but must match the one inside).

But that all hypothetical since we don't support encrypted ROs ;)

**Pull request merged**
