### PR TITLE
Allows overriding methods in default services

### PR DESCRIPTION
**Pull request by lacroixdavid1**

### CODE REVIEW

**Comment by brockallen** [comment]
We'd also want to promote any member variables to be protected, like we do elsewhere: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultTokenService.cs#L35

Also, we need you to sign the CLA, please.

**Comment by dfrunet** [comment]
@lacroixdavid1, class DefaultUserSession is still internal, so no external overrids allowed : (
Could you fix that as well, please?

**Comment by lacroixdavid1** [comment]
@dfrunet done

**Comment by brockallen** [comment]
Thanks!

**Pull request merged**
