### PR TITLE
use asynchronous EF methods

### PR DESCRIPTION
**Pull request by brockallen**
#2067

### CODE REVIEW

**Comment by AliBazzi** [comment]
Hi @brockallen ,

I think you overlooked [CorsPolicyService](https://github.com/IdentityServer/IdentityServer4/pull/3674/files#diff-d6171d6b788a414421fb4d52b1da4c9b).

And sorry for not making it apparent that a PR already exist for the same purpose.

**Comment by brockallen** [comment]
Good catch. I have now added it to the cors service. Thanks.

**Comment by leastprivilege** [comment]
The build seems to be dead-locking...

**Comment by AliBazzi** [comment]
Same happened with my PR, I don't know why is that with windows build only

**Comment by brockallen** [comment]
finally sorted out why it was deadlocking. done. merged. kthxbye.

**Pull request merged**
