### PR TITLE
Device Code Cleanup

### PR DESCRIPTION
**Pull request by scottbrady91**
Initial pass at cleaning up device flow codes added to `TokenCleanup`.

Includes breaking change on the `IOperationalStoreNotification` interface.

### CODE REVIEW

**Comment by scottbrady91** [comment]
Well the EF tests passed 🤷‍♂️

**Comment by brockallen** [comment]
So what's wrong with the build? // @leastprivilege

**Comment by brockallen** [comment]
Hey Scott -- can you resolve this conflict on this? Thanks

**Comment by leastprivilege** [comment]
That's a breaking change on the interface..

**Comment by scottbrady91** [comment]
Okay, I've removed the breaking change since you want this in 2.5. I'll open an issue to track the `IOperationalStoreNotification` update.

**Comment by brockallen** [comment]
great, thanks

**Pull request merged**
