### PR TITLE
Review1 changes

### PR DESCRIPTION
**Pull request by scottbrady91**
Device flow changes after initial review.

### Complete:
- Moved device codes & user codes into a single table (`IDeviceCodeStore`)
- Hashed codes when storing (`IDeviceCodeService`)
- Added consent to UI and interaction service (per authorization request)

### TODO:
- Consent templates based on remember consent
- Thread-safety check for `InMemoryDeviceFlowStore`
- Persisted grant description #2621

### CODE REVIEW

**Comment by leastprivilege** [comment]
I tried - getting a merge conflict...maybe you do that yourself ;)

**Comment by scottbrady91** [comment]
Okay, I tried a fresh PR of just the merge and the fixes. It's the merge which is causing the crazy commit length.

I think merging this is fine.

**Comment by scottbrady91** [comment]
You're a massive thing...

**Comment by brockallen** [comment]
> You're a massive thing...

I think GitHub is not the right place for [humour](https://github.com/Microsoft/msbuild/pull/1#issuecomment-83182329).

**Comment by scottbrady91** [comment]
Okay, that's all the changes for the core repo done.

The solution for the thread safety of the InMemoryDeviceFlowStore was to just "put a lock around it".

I've addressed the possibility for user code collisions using a retry policy and scrubbed the device code from the logs.

**Comment by brockallen** [comment]
I'd add another TODO: Add code comments for every `warning CS1591: Missing XML comment for publicly visible type or member`

**Comment by brockallen** [comment]
ok, here goes....

**Comment by brockallen** [comment]
whew, looks like it worked.

**Comment by brockallen** [comment]
oh wait -- this wasn't into dev... so where should or do we want this merged?

**Comment by scottbrady91** [comment]
It’s gone to #2284. That’ll need merging into dev

**Comment by brockallen** [comment]
Yea, well, that has conflicts now.

**Pull request merged**
