### PR TITLE
Update extension_grants.rst

### PR DESCRIPTION
**Pull request by rmja**
TokenErrors -> TokenRequestErrors

### CODE REVIEW

**Comment by leastprivilege** [comment]
thanks!

**Comment by rmja** [comment]
@leastprivilege Should there be some handling in the case where the sub claim is null? For example if the token was issued in a client credential flow. In fact, how is that even meant to work?

I was thinking along the lines of:

```
var subject = result.Claims.FirstOrDefault(c => c.Type == JwtClaimTypes.Subject)?.Value;

            if (subject != null)
            {
                context.Result = new GrantValidationResult(subject, "delegation");
            }
            else
            {
                // what to put here?
            }
```

**Comment by leastprivilege** [comment]
wrong place for discussion. open an issue. thanks

**Comment by rmja** [comment]
Sorry, Opened #775.

**Pull request merged**
