### PR TITLE
Token validation options

### PR DESCRIPTION
**Pull request by pecanw**
**What issue does this PR address?**
#4965 - Multiple valid issuers

**Does this PR introduce a breaking change?**
NO

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/IdentityServer/IdentityServer4?pullRequest=4967) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/IdentityServer/IdentityServer4?pullRequest=4967) before we can accept your contribution.<br/><br/>:x: pecanw [sign now](https://cla.dotnetfoundation.org/IdentityServer/IdentityServer4?pullRequest=4967)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/IdentityServer/IdentityServer4?pullRequest=4967) it.</sub>

**Comment by leastprivilege** [comment]
Thanks for your contribution!

IdentityServer4 is feature complete.

All new feature work will happen in our new [organization](https://github.com/duendesoftware). The new Duende IdentityServer is available under both a FOSS (RPL) and a commercial license. Development and testing is always free. [Contact](https://duendesoftware.com/contact) us for more information. 

This repo will be maintained with bug fixes and security updates until November 2022.

**Comment by leastprivilege** [comment]
That being said, you can implement this feature yourself using our standard extensibility - so you have a workaround.

**Comment by pecanw** [comment]
Can you advise me how to extend it? The `TokenValidator` is internal and there's no option to change the `TokenValidationParameters`:

```csharp
            var parameters = new TokenValidationParameters
            {
                ValidIssuer = _context.HttpContext.GetIdentityServerIssuerUri(),
                IssuerSigningKeys = validationKeys.Select(k => k.Key),
                ValidateLifetime = validateLifetime
            };
```

The only option is to write completely custom implementation of the `ITokenValidator` which is in general not a good idea. Even an ugly "copy-paste-rewrite" approach is not applicable as e.g `TokenValidationLog` is internal.

**Comment by leastprivilege** [comment]
Hm - OK - then I am wrong. Need to discuss this.

**Comment by leastprivilege** [comment]
I am sorry, but we are not making feature updates anymore to v4.

Feel free to do a feature request in our new repo, we are happy to discuss this.

https://github.com/DuendeSoftware/IdentityServer

**Pull request closed without merging**
