### PR TITLE
Get Ip from HTTP_X_FORWARDED_FOR if present, to handle proxies

### PR DESCRIPTION
**Pull request by ericgreenmix**

### CODE REVIEW

**Comment by brockallen** [comment]
how does the iis integration mw do this?

**Comment by ericgreenmix** [comment]
Yeah, I think you are right about this. Got it working as middleware instead. That does seem like a better place. closing

**Comment by damienbod** [comment]
Hi @ericgreenmix just wondering is this required, I was hoping that the framework set the RemoteIpAddress if that header or any of the other forward headers where used. What about all the other ones?

            //// "HTTP_X_COMING_FROM"
            //// "HTTP_X_FORWARDED_FOR"
            //// "HTTP_X_FORWARDED"
            //// "HTTP_X_REAL_IP"
            //// "HTTP_VIA"
            //// "HTTP_COMING_FROM"
            //// "HTTP_FORWARDED_FOR"
            //// "HTTP_FORWARDED"
            //// "HTTP_FROM"
            //// "HTTP_PROXY_CONNECTION"
            //// "CLIENT_IP"
            //// "FORWARDED"

Greetings Damien

**Comment by ericgreenmix** [comment]
We found with our nginx proxy to kestrel, we had to do the following...
```
app.Use(async (httpcontext, next) =>
{ 
    if (httpcontext.Request.Headers.ContainsKey("X-Forwarded-For"))
    {
        httpcontext.Connection.RemoteIpAddress = IPAddress.Parse(httpcontext.Request.Headers["X-Forwarded-For"]);
    }
    await next();
});
```

**Comment by damienbod** [comment]
Ok thanks, wondering if this is a bug or per intention, IIS sets this

**Pull request closed without merging**
