### PR TITLE
Adding note about NET452 runtime errors.

### PR DESCRIPTION
**Pull request by obosha**
Adding a note about runtime errors encountered when targeting NET452 during metadata endpoint retrieval.

### CODE REVIEW

**Comment by leastprivilege** [comment]
do you more info on the exact exception type?

**Comment by obosha** [comment]
Sure.  Wasnt sure how much detail you wanted in documentation.

I will add more info.

**Comment by obosha** [comment]
I added additional content and submitted a pull request.

**Comment by leastprivilege** [comment]
OK - something went wrong with this PR as you can see in your commit history.

No prob - i added the text manually. thanks!

**Pull request closed without merging**
