### PR TITLE
Removed scheme checking in cors origin validation.

### PR DESCRIPTION
**Pull request by pavinan**
**What issue does this PR address?**
Allows custom schemes in CORS Uri.

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] Unit Tests for the changes have been added (for bug fixes / features)
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/master/.github/CONTRIBUTING.md)

**Other information**:
Related to #3535

### CODE REVIEW

**Comment by MZap** [comment]
I was curious if this also needs to get fixed:
[EndSessionCallbackResult](https://github.com/IdentityServer/IdentityServer4/blob/97317677d714b31d7ae8b20b7de0810e81df74c5/src/IdentityServer4/src/Endpoints/Results/EndSessionCallbackResult.cs#L65)

I noticed it makes a call to GetOrigin [GetOrigin](https://github.com/IdentityServer/IdentityServer4/blob/97317677d714b31d7ae8b20b7de0810e81df74c5/src/IdentityServer4/src/Extensions/StringsExtensions.cs#L246)

` private void AddCspHeaders(HttpContext context)
        {
            if (_options.Authentication.RequireCspFrameSrcForSignout)
            {
                string frameSources = null;
                var origins = _result.FrontChannelLogoutUrls?.Select(x => x.GetOrigin());
                if (origins != null && origins.Any())
                {
                    frameSources = origins.Distinct().Aggregate((x, y) => $"{x} {y}");
                }

                // the hash matches the embedded style element being used below
                context.Response.AddStyleCspHeaders(_options.Csp, "sha256-u+OupXgfekP+x/f6rMdoEAspPCYUtca912isERnoEjY=", frameSources);
            }
        }`

It looks like if a null is returned from GetOrigin() this might impact somethings downstream



It would be nice to get a status update on this PR as well. We are about to move to use ID4 and don't want to fork this repo to avoid customization

**Comment by pavinan** [comment]
If removing scheme validation is going to be a security concern. It is better to give an option like a boolean property ``SuppressSchemeValidation``.

**Comment by brockallen** [comment]
> It would be nice to get a status update on this PR as well. We are about to move to use ID4 and don't want to fork this repo to avoid customization

Rarely do you need to fork this repo, as there are numerous extensibility points.

**Comment by MZap** [comment]
Hi Brock, this is very true. We are taking advantage of the DI framework and replacing the classes we need. Thanks!

**Pull request closed without merging**
