### PR TITLE
Spelling correction in startup.rst

### PR DESCRIPTION
**Pull request by surfsquid**
Corrected typo "implementes" => "implements"

### CODE REVIEW

**Comment by brockallen** [comment]
Is our CLA bot still working @leastprivilege @jongalloway?

**Comment by jongalloway** [comment]
Adding @MichaelTsengLZ to verify since we just flipped to new CLA system.

**Comment by MichaelTsengLZ** [comment]
Yes, its still working. But I found the logo is a little bit strange. 
screen shot 2017-12-08 at 1 49 30 pm

**Comment by brockallen** [comment]
> Yes, it's still working. But I found the logo is a little bit strange. I don't use label anymore.

Ah, so that's now where it shows up with the recent changes. Ok, thanks!

**Comment by brockallen** [comment]
Thanks @surfsquid!

**Comment by MichaelTsengLZ** [comment]
@brockallen, if the contributor has already signed the DNF CLA. It will silently shows the CLA success status. If the contributor hasn't signed the DNF CLA, we will have an explicit comment to remind the contributor to sign and also shows a CLA pending status. The goal of these changes is to make the CLA bot less chatty. Hope you like it. :)

**Comment by brockallen** [comment]
@MichaelTsengLZ yep, that all sounds great. thanks!

**Pull request merged**
