### PR TITLE
Wording fix in docs

### PR DESCRIPTION
**Pull request by ChrisSimmons**
"heads" -> "headers"

**What issue does this PR address?**

Wording issue in docs

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/main/.github/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)
  - N/A

### CODE REVIEW

**Comment by brockallen** [comment]
Thanks!

**Comment by brockallen** [comment]
Actually, after re-reading it... that is the intended wording there.

**Comment by ChrisSimmons** [comment]
Yikes, sorry about that.  I'll whip up a revert.

**Comment by ChrisSimmons** [comment]
N/m, I see you got it.  Disappearing now! :)

**Pull request merged**
