### PR TITLE
fix ??-operator priority

### PR DESCRIPTION
**Pull request by Backs**
**What issue does this PR address?**
No issue

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x ] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/dev/.github/CONTRIBUTING.md)
- [ x] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by brockallen** [comment]
@leastprivilege maybe we can have a look at this monday. i don't know what the side effect of this change might be.

**Comment by brockallen** [comment]
> What issue does this PR address?
> No issue

Can you explain why the change is right or better? Thanks.

**Comment by Backs** [comment]
@brockallen problem is that `GetHashCode` will return `0` if `Value` or `Type` is null. So
`new Secret("a").GetHashCode() == new Secret("b").GetHashCode()`
And it's not the behavior you expect, I think.

**Comment by leastprivilege** [comment]
I will have to merge manually since this file has moved.

**Pull request closed without merging**
