### PR TITLE
Change sdk version from 2 to 2.x

### PR DESCRIPTION
**Pull request by LindaLawton**
**What issue does this PR address?**

no

**Does this PR introduce a breaking change?**

no

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/dev/.github/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:

I will have a look at the tutorials but I think the sample project would also need to be updated if we do that.

### CODE REVIEW

**Comment by LindaLawton** [comment]
Ha what?

@leastprivilege you merged the 2.1 change in right?   That built fine didnt it?

**Comment by leastprivilege** [comment]
The Linux build is not working yet...

**Comment by LindaLawton** [comment]
OK as long as its not something i broke :)

**Comment by leastprivilege** [comment]
How about 2.x ?

**Comment by LindaLawton** [comment]
Yeah I was thinking the same but if we need to have a specific version of the SDK installed to run it it may be best to hard code it.  Right now we are on 2.1,  but if they release 2.2 will it work out of the box with 2.2 probably not until we upgrade to that.   It definitely wont work if you have 2.0 on your machine.  Which is technically .x

But yes this means we will need to update this file every time we change.   Which is not to much of a problem i am good at remembering to do random stuff like this.

You decide.

**Comment by leastprivilege** [comment]
The dev branch will always be on the latest 2.x SDK

**Comment by LindaLawton** [comment]
Updated

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
